From 35c49f6dcf6c7855790dcd2add33247387be072a Mon Sep 17 00:00:00 2001
From: Matteo Bertozzi <matteo.bertozzi@cloudera.com>
Date: Wed, 26 Dec 2012 15:17:15 +0000
Subject: [PATCH 105/202] HBASE-7436 Improve stack trace info dumped by ForeignExceptionSnare#rethrowException

Reason: Snapshots
Author: Jonathan Hsieh
Ref: CDH-9551
---
 .../errorhandling/ForeignExceptionDispatcher.java  |    4 +++-
 .../TestForeignExceptionDispatcher.java            |    2 +-
 2 files changed, 4 insertions(+), 2 deletions(-)

diff --git a/src/main/java/org/apache/hadoop/hbase/errorhandling/ForeignExceptionDispatcher.java b/src/main/java/org/apache/hadoop/hbase/errorhandling/ForeignExceptionDispatcher.java
index 441219b..17aceb0 100644
--- a/src/main/java/org/apache/hadoop/hbase/errorhandling/ForeignExceptionDispatcher.java
+++ b/src/main/java/org/apache/hadoop/hbase/errorhandling/ForeignExceptionDispatcher.java
@@ -87,7 +87,9 @@ public class ForeignExceptionDispatcher implements ForeignExceptionListener, For
   @Override
   public void rethrowException() throws ForeignException {
     if (exception != null) {
-      throw exception;
+      // This gets the stack where this is caused, (instead of where it was deserialized).
+      // This which is much more useful for debugging
+      throw new ForeignException(exception.getSource(), exception.getCause());
     }
   }
 
diff --git a/src/test/java/org/apache/hadoop/hbase/errorhandling/TestForeignExceptionDispatcher.java b/src/test/java/org/apache/hadoop/hbase/errorhandling/TestForeignExceptionDispatcher.java
index c969ae4..0e876a4 100644
--- a/src/test/java/org/apache/hadoop/hbase/errorhandling/TestForeignExceptionDispatcher.java
+++ b/src/test/java/org/apache/hadoop/hbase/errorhandling/TestForeignExceptionDispatcher.java
@@ -68,7 +68,7 @@ public class TestForeignExceptionDispatcher {
       dispatcher.rethrowException();
       fail("Monitor should have thrown an exception after getting error.");
     } catch (ForeignException ex) {
-      assertTrue("Got an unexpected exception:" + ex, ex == EXTEXN);
+      assertTrue("Got an unexpected exception:" + ex, ex.getCause() == EXTEXN.getCause());
       LOG.debug("Got the testing exception!");
     }
 
-- 
1.7.0.4

