From dd1a5a659da496968a2e1ab580f89bcdbe312bf6 Mon Sep 17 00:00:00 2001
From: Carl Steinbach <carl@cloudera.com>
Date: Thu, 8 Mar 2012 20:41:04 -0800
Subject: [PATCH 34/58] HIVE-2857. QTestUtil.cleanUp() fails with FileNotException on 0.23

Reason: Bug
Author: Carl Steinbach
Ref: CDH-4626
---
 .../test/org/apache/hadoop/hive/ql/QTestUtil.java  |   11 ++++++++---
 1 files changed, 8 insertions(+), 3 deletions(-)

diff --git a/src/ql/src/test/org/apache/hadoop/hive/ql/QTestUtil.java b/src/ql/src/test/org/apache/hadoop/hive/ql/QTestUtil.java
index 65516f9..da98f19 100644
--- a/src/ql/src/test/org/apache/hadoop/hive/ql/QTestUtil.java
+++ b/src/ql/src/test/org/apache/hadoop/hive/ql/QTestUtil.java
@@ -382,9 +382,14 @@ public class QTestUtil {
     // delete any contents in the warehouse dir
     Path p = new Path(testWarehouse);
     FileSystem fs = p.getFileSystem(conf);
-    FileStatus [] ls = fs.listStatus(p);
-    for (int i=0; (ls != null) && (i<ls.length); i++) {
-      fs.delete(ls[i].getPath(), true);
+
+    try {
+      FileStatus [] ls = fs.listStatus(p);
+      for (int i=0; (ls != null) && (i<ls.length); i++) {
+        fs.delete(ls[i].getPath(), true);
+      }
+    } catch (FileNotFoundException e) {
+      // Best effort
     }
 
     FunctionRegistry.unregisterTemporaryUDF("test_udaf");
-- 
1.7.0.4

